namespace NeoTwitch.Services.Text;

public static class SpanishUiTextCatalog
{
    public static IReadOnlyDictionary<string, string> Create()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [UiTextKeys.AudioTitle] = "Audio",
            [UiTextKeys.ImagesTitle] = "Imagenes",
            [UiTextKeys.VideosTitle] = "Videos",

            [UiTextKeys.LibraryNoGroup] = "Sin grupo",
            [UiTextKeys.LibraryNoGroupAssigned] = "Sin grupo asignado",
            [UiTextKeys.LibraryNoAlertAssigned] = "Sin alerta asignada",
            [UiTextKeys.LibrarySelectedGroup] = "seleccionado",

            [UiTextKeys.LibraryWriteGroupName] = "Escribe un nombre para el grupo.",
            [UiTextKeys.LibraryDeleteAssetPrompt] = "Eliminar '{0}' de la biblioteca?",
            [UiTextKeys.LibraryDeleteGroupPrompt] = "Eliminar el grupo '{0}'?\n\nLos {1} archivo(s) no se borran; solo quedaran sin grupo.",
            [UiTextKeys.LibrarySavedLog] = "{0}: guardado {1}.",
            [UiTextKeys.LibraryGroupCreatedLog] = "{0}: grupo creado {1}.",
            [UiTextKeys.LibraryShowingGroupLog] = "{0}: mostrando grupo {1}.",
            [UiTextKeys.LibraryGroupDeletedLog] = "{0}: grupo eliminado {1}.",
            [UiTextKeys.LibraryLastUnused] = "Sin uso",
            [UiTextKeys.LibraryFileCount] = "{0} archivo{1}",

            [UiTextKeys.AudioPickValidFile] = "Selecciona un archivo de audio valido.",
            [UiTextKeys.AudioPlayingLog] = "Audio: reproduciendo {0}.",

            [UiTextKeys.MediaPickValidFile] = "Selecciona un archivo valido para {0}.",
            [UiTextKeys.MediaObsConnectRequiredLog] = "OBS: conecta OBS antes de probar imagenes o videos.",
            [UiTextKeys.MediaObsConnectRequiredPrompt] = "Conecta OBS desde Conexiones antes de probar imagenes o videos.",
            [UiTextKeys.MediaObsMissingFileLog] = "OBS: el archivo seleccionado no existe.",
            [UiTextKeys.MediaObsMissingSceneLog] = "OBS: no hay una escena actual para probar el medio.",
            [UiTextKeys.MediaObsPreviewLog] = "OBS: probando {0} '{1}'.",

            [UiTextKeys.DiagnosticsWindowTitle] = "Diagnostico Neo Twitch",
            [UiTextKeys.DiagnosticsNoWarningsTitle] = "Diagnostico sin advertencias",
            [UiTextKeys.DiagnosticsWarningsTitle] = "Diagnostico con {0} punto(s) por revisar",
            [UiTextKeys.DiagnosticsCopyReport] = "Copiar reporte",
            [UiTextKeys.DiagnosticsClose] = "Cerrar",
            [UiTextKeys.DiagnosticsCopiedLog] = "Diagnostico copiado al portapapeles.",
            [UiTextKeys.DiagnosticsSuccessLog] = "Diagnostico: sin advertencias.",
            [UiTextKeys.DiagnosticsWarningsLog] = "Diagnostico: {0} punto(s) por revisar.",
            [UiTextKeys.DiagnosticsTitle] = "Diagnostico",
            [UiTextKeys.DiagnosticsFailureCrash] = "No se pudo ejecutar el diagnostico.",
            [UiTextKeys.DiagnosticsFailureLog] = "Diagnostico: {0}",

            [UiTextKeys.TwitchTitle] = "Twitch",
            [UiTextKeys.TwitchLoginTitle] = "Login Twitch",
            [UiTextKeys.TwitchDisconnectedLog] = "Twitch desconectado.",
            [UiTextKeys.TwitchMissingClientId] = "Escribe primero el Client ID de Twitch.",
            [UiTextKeys.TwitchAuthorizePrompt] = "Autoriza la app en Twitch con el codigo {0}. El codigo ya quedo copiado al portapapeles.",
            [UiTextKeys.TwitchAuthorizedLog] = "Twitch autorizado como {0}.",
            [UiTextKeys.TwitchMissingScopes] = "Twitch necesita autorizar permisos nuevos: {0}. Presiona Conectar Twitch para iniciar sesion otra vez.",
            [UiTextKeys.TwitchReauthRequiredLog] = "Twitch necesita autorizar de nuevo porque el token guardado no se pudo refrescar.",
            [UiTextKeys.TwitchListeningLog] = "Twitch escuchando eventos.",

            [UiTextKeys.ObsRuleMissingMediaLog] = "OBS: la regla '{0}' no tiene un archivo valido para mostrar.",
            [UiTextKeys.ObsRuleMissingSceneLog] = "OBS: no hay una escena actual para mostrar el medio.",
            [UiTextKeys.ObsRuleMediaShownLog] = "OBS: medio '{0}' mostrado en '{1}'.",
            [UiTextKeys.ObsRuleMediaHiddenLog] = "OBS: medio oculto en '{0}'.",

            [UiTextKeys.BackgroundAlexaOnTitle] = "Fondo Alexa encendido",
            [UiTextKeys.BackgroundAlexaOffTitle] = "Fondo Alexa apagado",
            [UiTextKeys.BackgroundMissingComLog] = "No puedo aplicar fondo sin puerto COM.",
            [UiTextKeys.BackgroundArduinoConnectFailureLog] = "Arduino: no pude aplicar fondo en {0}. Revisa el puerto y conecta manualmente.",
            [UiTextKeys.BackgroundArduinoConnectFailureCrash] = "No se pudo conectar Arduino para aplicar fondo en {0}.",
            [UiTextKeys.BackgroundAppliedLog] = "Fondo aplicado: {0}.",
            [UiTextKeys.BackgroundAlexaSentLog] = "Alexa fondo: {0}.",
            [UiTextKeys.BackgroundAlexaFailureCrash] = "No se pudo enviar fondo Alexa '{0}'.",
            [UiTextKeys.BackgroundAlexaFailureLog] = "Alexa fondo: {0}",
            [UiTextKeys.BackgroundScheduledFailureCrash] = "No se pudo aplicar el fondo programado.",
            [UiTextKeys.BackgroundScheduledFailureLog] = "Fondo: {0}",

            [UiTextKeys.SettingsAutomaticBackupsText] = "Backups automaticos: {0}",
            [UiTextKeys.SettingsManualBackupText] = "Ultimo backup manual: {0}",
            [UiTextKeys.SettingsSavedLog] = "Configuracion guardada.",
            [UiTextKeys.SettingsBackupTitle] = "Backups",
            [UiTextKeys.SettingsBackupCreatedLog] = "Backup creado: {0}",
            [UiTextKeys.SettingsBackupSuccessPrompt] = "Backup creado correctamente.",
            [UiTextKeys.SettingsBackupCreateFailureCrash] = "No se pudo crear un backup manual.",
            [UiTextKeys.SettingsBackupCreateFailureLog] = "Backups: no pude crear backup ({0}).",
            [UiTextKeys.SettingsRestoreBackupTitle] = "Restaurar backup",
            [UiTextKeys.SettingsBackupFileFilter] = "Backup Neo Twitch (*.json)|*.json|Todos los archivos (*.*)|*.*",
            [UiTextKeys.SettingsRestoreBackupPrompt] = "Restaurar este backup reemplazara la configuracion actual. Se creara un backup automatico antes de guardar.\n\nQuieres continuar?",
            [UiTextKeys.SettingsBackupRestoredLog] = "Backup restaurado: {0}",
            [UiTextKeys.SettingsBackupRestoreSuccessPrompt] = "Backup restaurado correctamente. Revisa Twitch, Arduino y Alexa antes de salir en vivo.",
            [UiTextKeys.SettingsBackupRestoreFailureCrash] = "No se pudo restaurar el backup.",
            [UiTextKeys.SettingsBackupRestoreFailureLog] = "Backups: no pude restaurar ({0}).",
            [UiTextKeys.SettingsExportTitle] = "Exportar configuracion",
            [UiTextKeys.SettingsImportTitle] = "Importar configuracion",
            [UiTextKeys.SettingsTitle] = "Configuracion",
            [UiTextKeys.SettingsConfigFileFilter] = "Configuracion Neo Twitch (*.json)|*.json|Todos los archivos (*.*)|*.*",
            [UiTextKeys.SettingsExportedLog] = "Configuracion exportada: {0}",
            [UiTextKeys.SettingsExportSuccessPrompt] = "Configuracion exportada correctamente.\n\nEste archivo puede incluir tokens, URLs o secretos privados. Guardalo en un lugar seguro.",
            [UiTextKeys.SettingsExportFailureCrash] = "No se pudo exportar la configuracion.",
            [UiTextKeys.SettingsExportFailureLog] = "Configuracion: no pude exportar ({0}).",
            [UiTextKeys.SettingsImportPrompt] = "Importar esta configuracion reemplazara la configuracion actual. Se creara un backup automatico antes de guardar.\n\nQuieres continuar?",
            [UiTextKeys.SettingsImportedLog] = "Configuracion importada: {0}",
            [UiTextKeys.SettingsImportSuccessPrompt] = "Configuracion importada correctamente. Revisa Twitch, Arduino y Alexa antes de salir en vivo.",
            [UiTextKeys.SettingsImportFailureCrash] = "No se pudo importar la configuracion.",
            [UiTextKeys.SettingsImportFailureLog] = "Configuracion: no pude importar ({0}).",

            [UiTextKeys.ConnectionConnected] = "Conectado",
            [UiTextKeys.ConnectionDisconnected] = "Desconectado",
            [UiTextKeys.ConnectionDisabled] = "Desactivado",
            [UiTextKeys.ConnectionConnecting] = "Conectando",
            [UiTextKeys.ConnectionWarningReview] = "Revisar",
            [UiTextKeys.ConnectionWarningNoResponse] = "Sin respuesta",
            [UiTextKeys.ConnectionWarningConfigured] = "Configurado",
            [UiTextKeys.ConnectionWarningIncomplete] = "Incompleta",
            [UiTextKeys.AppStateOk] = "Estado: Todo en orden",
            [UiTextKeys.AppStateWarning] = "Estado: Hay puntos por revisar",
            [UiTextKeys.AppStateError] = "Estado: Revisa el diagnostico",
            [UiTextKeys.ConnectionButtonTwitchAuthorizing] = "Autorizando...",
            [UiTextKeys.ConnectionButtonConnecting] = "Conectando...",
            [UiTextKeys.ConnectionButtonTwitchDisconnect] = "Desconectar Twitch",
            [UiTextKeys.ConnectionButtonTwitchConnect] = "Conectar Twitch",
            [UiTextKeys.ConnectionButtonArduinoConnect] = "Conectar Arduino",
            [UiTextKeys.ConnectionButtonAlexaTesting] = "Probando...",
            [UiTextKeys.ConnectionButtonAlexaTest] = "Probar Alexa",
            [UiTextKeys.ConnectionButtonObsDisconnect] = "Desconectar OBS",
            [UiTextKeys.ConnectionButtonObsConnect] = "Conectar OBS",
            [UiTextKeys.ConnectionButtonObsScenesUpdating] = "Actualizando...",
            [UiTextKeys.ConnectionButtonObsScenesRefresh] = "Actualizar escenas",
            [UiTextKeys.NavPanel] = "Panel",
            [UiTextKeys.NavConnections] = "Conexiones",
            [UiTextKeys.NavAlerts] = "Alertas",
            [UiTextKeys.NavLights] = "Luces",
            [UiTextKeys.NavAlexa] = "Alexa",
            [UiTextKeys.NavAudio] = "Audio",
            [UiTextKeys.NavImages] = "Imagenes",
            [UiTextKeys.NavVideos] = "Videos",
            [UiTextKeys.NavObs] = "OBS",
            [UiTextKeys.NavConfiguration] = "Configuracion",
            [UiTextKeys.NavActivity] = "Actividad",
            [UiTextKeys.TwitchLive] = "En directo",
            [UiTextKeys.TwitchOffline] = "No esta en directo",
            [UiTextKeys.TwitchProfile] = "Perfil",
            [UiTextKeys.ObsReviewConnection] = "Revisar conexion",
            [UiTextKeys.ObsDisabledStatusText] = "OBS desactivado. Las acciones OBS no se mostraran ni ejecutaran.",
            [UiTextKeys.ObsConnectedStatusText] = "OBS conectado en {0}:{1}.",
            [UiTextKeys.ObsConnectPromptStatusText] = "Conecta OBS Studio para leer escenas y preparar automatizaciones.",
            [UiTextKeys.ObsNoScene] = "Sin escena",
            [UiTextKeys.ObsDefaultHost] = "127.0.0.1",
            [UiTextKeys.ObsNoVersion] = "Sin version",
            [UiTextKeys.ObsStudioModeEnabled] = "Activado",
            [UiTextKeys.ObsStudioModeDisabled] = "Desactivado",
            [UiTextKeys.ObsKeepCurrentScene] = "Mantener escena actual",

            [UiTextKeys.TrayBackgroundTitle] = "{0} sigue activo",
            [UiTextKeys.TrayBackgroundText] = "La app quedo en segundo plano. Abrela desde el icono de la bandeja cuando la necesites.",
            [UiTextKeys.TrayHiddenLog] = "Ventana oculta en segundo plano.",

            [UiTextKeys.UpdateUpToDateLog] = "Version: V{0} al dia.",
            [UiTextKeys.UpdateAvailableLog] = "Version: hay una nueva version V{0}.",
            [UiTextKeys.UpdatePromptInPlace] = "Hay una nueva version de Neo Twitch.\n\nTu version: V{0}\nUltima version: V{1}\n\nQuieres actualizar ahora? La app se cerrara un momento y el instalador hara el reemplazo.",
            [UiTextKeys.UpdatePromptReleasePage] = "Hay una nueva version de Neo Twitch.\n\nTu version: V{0}\nUltima version: V{1}\n\nNo encontre el instalador local. Quieres abrir la pagina de releases para descargarla?",
            [UiTextKeys.UpdateAvailableTitle] = "Actualizacion disponible",
            [UiTextKeys.UpdateCheckFailedLog] = "Version: no pude consultar actualizaciones ({0}).",
            [UiTextKeys.UpdateLaunchingInstallerLog] = "Version: iniciando actualizador a V{0}.",
            [UiTextKeys.UpdateLaunchFailedLog] = "Version: no pude abrir el actualizador ({0}).",

            [UiTextKeys.AppAlreadyOpenMessage] = "{0} ya esta abierta. Revisa el icono en la bandeja del sistema.",
            [UiTextKeys.AppStartupFailureLog] = "Fallo al iniciar la aplicacion.",
            [UiTextKeys.AppUiUnhandledLog] = "Fallo no controlado en la interfaz.",
            [UiTextKeys.AppProcessUnhandledLog] = "Fallo no controlado del proceso.",
            [UiTextKeys.AppProcessUnhandledObjectLog] = "Fallo no controlado del proceso: {0}",
            [UiTextKeys.AppBackgroundTaskUnhandledLog] = "Fallo no observado en una tarea en segundo plano.",
            [UiTextKeys.AppFatalErrorMessage] = "La app no pudo iniciar correctamente.\n\nDetalle: {0}\n\nLog: {1}",
            [UiTextKeys.StartupReadyLog] = "Aplicacion lista.",
            [UiTextKeys.StartupSettingsPathLog] = "Configuracion: {0}",
            [UiTextKeys.StartupCrashLogPathLog] = "Log de errores: {0}",
            [UiTextKeys.StartupPreviousSettingsReadFailureLog] = "No pude leer la configuracion anterior: {0}",
            [UiTextKeys.StartupDebugModeLog] = "Modo debug activo.",
            [UiTextKeys.StartupAutoConnectSuppressedLog] = "Conexiones automaticas omitidas por opciones de depuracion.",
            [UiTextKeys.StartupArduinoAutoConnectFailureCrash] = "No se pudo conectar Arduino automaticamente en {0}.",
            [UiTextKeys.StartupArduinoAutoConnectFailureLog] = "Arduino: no pude conectar {0}. Las luces quedan desactivadas hasta reconectar el puerto."
        };
    }
}
