using System.Windows;
using NeoTwitch.Models;
using NeoTwitch.Services;
using NeoTwitch.Services.Lights;
using NeoTwitch.Services.Ui;
using NeoTwitch.ViewModels.Library;
using NeoTwitch.ViewModels.Obs;
using NeoTwitch.ViewModels.Ui;
using DrawingIcon = System.Drawing.Icon;
using Forms = System.Windows.Forms;

namespace NeoTwitch;

public partial class MainWindow
{
    private const int LightStopSettleMs = 120;
    private static readonly TimeSpan AlertStreamStatusRefreshInterval = TimeSpan.FromSeconds(5);
    private readonly Random _previewRandom = new();
    private readonly Random _audioRandom = new();
    private readonly SemaphoreSlim _effectGate = new(1, 1);
    private readonly SemaphoreSlim _streamStatusRefreshGate = new(1, 1);
    private IReadOnlyList<SerialPortInfo> _availablePorts = [];
    private readonly IReadOnlyList<UiOption<TwitchEventKind>> _eventOptions;
    private readonly IReadOnlyList<UiOption<string>> _ruleCategoryOptions;
    private readonly IReadOnlyList<UiOption<LightPattern>> _patternOptions;
    private readonly IReadOnlyList<UiOption<string>> _themeModeOptions;
    private readonly IReadOnlyList<UiOption<ObsMediaKind>> _obsMediaKindOptions;
    private readonly IReadOnlyList<UiOption<MediaSourceMode>> _mediaSourceModeOptions;

    private AppConfig _config = new();
    private bool _initializingComponent;
    private bool _loadingUi;
    private bool _loadingRule;
    private bool _loadingStrip;
    private bool _isExiting;
    private bool _showClientId;
    private bool _showClientSecret;
    private bool _showAlexaRelayUrl;
    private bool _showAlexaAuthToken;
    private bool _showObsPassword;
    private bool _alexaRelayConnected;
    private bool _isObsConnecting;
    private bool _isTwitchAuthorizing;
    private bool _isTwitchConnecting;
    private bool _isArduinoConnecting;
    private bool _isAlexaConnecting;
    private bool _isCustomMaximized;
    private bool _isObsSceneActionRunning;
    private bool _hasUnsavedRuleChanges;
    private bool _suppressRuleSelectionChange;
    private bool _updatingLightValueFields;
    private bool _arduinoMonitorBusy;
    private bool _lastArduinoPortPresent = true;
    private bool? _lastAppliedStartWithWindows;
    private Rect _restoreWindowBounds = Rect.Empty;
    private DateTimeOffset _lastArduinoReconnectAttempt = DateTimeOffset.MinValue;
    private string _twitchConnectionError = "";
    private string _obsConnectionError = "";
    private bool _refreshingAudioLibrary;
    private bool _refreshingImageLibrary;
    private bool _refreshingVideoLibrary;
    private string _audioGroupChoicesSignature = "";
    private string _audioAlertChoicesSignature = "";
    private string _imageGroupChoicesSignature = "";
    private string _videoGroupChoicesSignature = "";
    private CancellationTokenSource? _backgroundApplyDebounce;
    private CancellationTokenSource? _twitchSubscriptionRefreshDebounce;
    private CancellationTokenSource? _currentEffectCts;
    private string _eventSubscriptionSignature = "";
    private bool _hasShownTrayNotice;
    private int _ruleLedPreviewStep;
    private int _backgroundLedPreviewStep;
    private AudioPlayback? _currentPlayback;
    private AudioPlayback? _audioPreviewPlayback;
    private string _previewingAudioId = "";
    private CancellationTokenSource? _mediaPreviewCts;
    private string _previewingMediaId = "";
    private MediaLibraryKind? _previewingMediaKind;
    private ObsMediaHideRequest? _mediaPreviewHideRequest;
    private ObsSceneRestoreRequest? _currentObsRestore;
    private ObsMediaHideRequest? _currentObsMediaHide;
    private bool _currentObsCleanedByStop;
    private EventRule? _editingRule;
    private EventRule? _loadedRuleSnapshot;
    private TwitchStreamStatus? _streamStatus;
    private DateTimeOffset _lastStreamStatusRefreshAt = DateTimeOffset.MinValue;
    private DrawingIcon? _trayIcon;
    private Forms.NotifyIcon? _notifyIcon;

}
