<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>NeoTwitch</AssemblyName>
    <Product>Neo Twitch</Product>
    <FileDescription>Neo Twitch</FileDescription>
    <Version>2.2.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;artifacts\**;..\artifacts\**</DefaultItemExcludes>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\AppIcon.png" />
    <Resource Include="Assets\ServiceAlexa.png" />
    <Resource Include="Assets\ServiceArduino.png" />
    <Resource Include="Assets\ServiceAudio.png" />
    <Resource Include="Assets\ServiceObs.png" />
    <Resource Include="Assets\ServiceTwitch.png" />
    <Resource Include="Assets\Icons\*.png" />
  </ItemGroup>

</Project>
